name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Generate C code
        run: python generator/generate.py specs.led
      - name: Check drift
        run: |
          if git diff --exit-code generated/; then
            echo "No drift"
          else
            echo "::error ::Generated files out of date! Regenerate and commit."
            git diff generated/
            exit 1
          fi
      - name: Run simulation
        run: python sim/run.py
